### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by xiao-kong-long** [BiomedicalMachineLearning/stLearn#197]
hello, I have installed stlearn as the conda version's instruction of https://readthedocs.org/projects/stlearn/, but when I was running the code "import stlearn as st", error occured. Error information is as follows:
`Traceback (most recent call last):
  File "D:/pyprog/papers_code/stlearn_test/test.py", line 1, in <module>
    import stlearn as st
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\stlearn\__init__.py", line 8, in <module>
    from . import add
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\stlearn\add.py", line 1, in <module>
    from .adds.add_image import image
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\stlearn\adds\add_image.py", line 2, in <module>
    from anndata import AnnData
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\anndata\__init__.py", line 7, in <module>
    from ._core.anndata import AnnData, ImplicitModificationWarning
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\anndata\_core\anndata.py", line 23, in <module>
    from scipy import sparse
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "E:\application\Anaconda3\envs\stlearn\lib\site-packages\scipy\_distributor_init.py", line 59, in <module>
    WinDLL(os.path.abspath(filename))
  File "E:\application\Anaconda3\envs\stlearn\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\application\Anaconda3\envs\stlearn\lib\site-packages\scipy\.libs\libbanded5x.7PE4S675VJ62Q2FNVPMD7F5FIF53EQIT.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Process finished with exit code 1`
I don't have knowledge of solving this. And anyone meet this?

**Comment by xiao-kong-long** [comment]
The pip version's installation is OK.

**Comment by duypham2108** [comment]
Thanks for reporting this issue. We will test the conda version again
