### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by wang0430** [BiomedicalMachineLearning/stLearn#224]
I installed the python3.8 environment using conda on linux, and then downloaded stlearn using pip, but I will report an error when importing.

>>> import stlearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/__init__.py", line 11, in <module>
    from . import tl
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/tl.py", line 1, in <module>
    from .tools import clustering
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/tools/clustering/__init__.py", line 3, in <module>
    from .annotate import annotate_interactive
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/tools/clustering/annotate.py", line 2, in <module>
    from stlearn.plotting.classes_bokeh import Annotate
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/plotting/classes_bokeh.py", line 50, in <module>
    from stlearn.classes import Spatial
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/classes.py", line 14, in <module>
    from .utils import (
  File "/home/wanggl/miniconda3/envs/TumorBoundary/lib/python3.8/site-packages/stlearn/utils.py", line 29, in <module>
    class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by duypham2108** [comment]
Please check this solution. We will try to solve this issue soon
https://github.com/BiomedicalMachineLearning/stLearn/issues/223#issuecomment-1436914147

**Comment by wang0430** [comment]
Thanks, duypham2108 !

I can import stLearn successfully!
