### ISSUE TITLE
AttributeError when adding annotation to clusters in trajectory analysis

### ISSUE THREAD

**Issue by fuerzhou** [BiomedicalMachineLearning/stLearn#240]
Hi @duypham2108,

Thank you for providing the tool for spatial data analysis.

I ran into this error when running through the spatial trajectory analysis tutorial using the example data:

```
>>> st.pl.cluster_plot(data,use_label="louvain",image_alpha=1,size=7)
>>> st.add.annotation(data,label_list=['Fatty tissue,immune/lymphoid 1 MALAT1+',
...                                    'Invasive cancer,fibrous tissue 1 CXCL14+',
...                                    'Invasive cancer,fibrous tissue 2 CRISP3+',
...                                    'Invasive cancer,fibrous tissue, fatty tissue',
...                                    'Fatty tissue,immune/lymphoid 2 IGKC+',
...                                    'Fibrous tissue',
...                                    'Invasive cancer,fibrous tissue (DCIS)',
...                                    'Fatty tissue, Fibrous tissue',
...                                    'Invasive cancer,immune/lymphoid (IDC)' ,
...                                    'Invasive cancer,fatty tissue 3 MUC5B+',
...                                    'Fatty tissue'],
...                  use_label="louvain")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/env/lib/python3.8/site-packages/stlearn/adds/annotation.py", line 42, in annotation
    adata.obs[use_label + "_anno"].cat.categories = label_list
  File "/opt/env/lib/python3.8/site-packages/pandas/core/base.py", line 178, in __setattr__
    object.__setattr__(self, key, value)
  File "/opt/env/lib/python3.8/site-packages/pandas/core/accessor.py", line 99, in _setter
    return self._delegate_property_set(name, new_values)
  File "/opt/env/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 2460, in _delegate_property_set
    return setattr(self._parent, name, new_values)
AttributeError: can't set attribute
```

I am using python3.8 and not sure if the error was caused by package versions. However, I was not able to install stlearn with any other version of Python. Could you please help me look into the issue? 

Thank you!
Yuzhou

**Comment by duypham2108** [comment]
Sorry for the late reply.
You can use this code instead. The old code seems to be not working anymore

```
data.obs.louvain.cat.rename_categories = ['Fatty tissue,immune/lymphoid 1 MALAT1+',
'Invasive cancer,fibrous tissue 1 CXCL14+',
'Invasive cancer,fibrous tissue 2 CRISP3+',
'Invasive cancer,fibrous tissue, fatty tissue',
'Fatty tissue,immune/lymphoid 2 IGKC+',
'Fibrous tissue',
'Invasive cancer,fibrous tissue (DCIS)',
'Fatty tissue, Fibrous tissue',
'Invasive cancer,immune/lymphoid (IDC)' ,
'Invasive cancer,fatty tissue 3 MUC5B+',
'Fatty tissue']
```

**Comment by fuerzhou** [comment]
Thank you for the reply. I used the code above to replace the `st.add.annotation()` part and got a different error:

```
>>> st.pl.cluster_plot(data,use_label="louvain",image_alpha=1,size=7)
>>> data.obs.louvain = data.obs.louvain.cat.rename_categories(['Fatty tissue,immune/lymphoid 1 MALAT1+',
                                          'Invasive cancer,fibrous tissue 1 CXCL14+',
                                          'Invasive cancer,fibrous tissue 2 CRISP3+',
                                          'Invasive cancer,fibrous tissue, fatty tissue',
                                          'Fatty tissue,immune/lymphoid 2 IGKC+',
                                          'Fibrous tissue',
                                          'Invasive cancer,fibrous tissue (DCIS)',
                                          'Fatty tissue, Fibrous tissue',
                                          'Invasive cancer,immune/lymphoid (IDC)' ,
                                          'Invasive cancer,fatty tissue 3 MUC5B+',
                                          'Fatty tissue'])

Louvain cluster is done! The labels are stored in adata.obs['louvain']
Traceback (most recent call last):
  File "spatial_traj.py", line 49, in <module>
    st.pl.cluster_plot(data,use_label="louvain_anno",image_alpha=1,size=7)
  File "/opt/env/lib/python3.8/site-packages/stlearn/plotting/cluster_plot.py", line 87, in cluster_plot
    ClusterPlot(
  File "/opt/env/lib/python3.8/site-packages/stlearn/plotting/classes.py", line 661, in __init__
    super().__init__(
  File "/opt/env/lib/python3.8/site-packages/stlearn/plotting/classes.py", line 83, in __init__
    assert (
AssertionError: Please choose the right label in `adata.obs.columns`!
```

Does this have anything to do with the category names? 

Yuzhou

**Comment by duypham2108** [comment]
You can create a new one first and rename later

```
data.obs["louvain_anno"] = data.obs.louvain.copy()

data.obs.louvain_anno = data.obs.louvain_anno.cat.rename_categories(['Fatty tissue,immune/lymphoid 1 MALAT1+',
'Invasive cancer,fibrous tissue 1 CXCL14+',
'Invasive cancer,fibrous tissue 2 CRISP3+',
'Invasive cancer,fibrous tissue, fatty tissue',
'Fatty tissue,immune/lymphoid 2 IGKC+',
'Fibrous tissue',
'Invasive cancer,fibrous tissue (DCIS)',
'Fatty tissue, Fibrous tissue',
'Invasive cancer,immune/lymphoid (IDC)' ,
'Invasive cancer,fatty tissue 3 MUC5B+',
'Fatty tissue'])

```

**Comment by fuerzhou** [comment]
Thank you very much for the help @duypham2108 ! This is working now.
