### ISSUE TITLE
Installation issue on Macbook M1 

### ISSUE THREAD

**Issue by Kennyluo4** [BiomedicalMachineLearning/stLearn#249]
Hello,
I have issue installing stLearn on my M1 mac. Can you help with it? 

Here is the error message from conda install `conda install -c conda-forge stlearn`:

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__unix==0=0
  - stlearn -> click[version='>=8.0.4'] -> __unix
  - stlearn -> click[version='>=8.0.4'] -> __win

Your installed version is: 0

Note that strict channel priority may have removed packages required for satisfiability.
```

pip install also failed with error:

```
Collecting tables (from scanpy>=1.8.2->stlearn)
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      ld: library not found for -llzo2
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -llzo
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      def _dump_h5_backtrace():
          cdef object bt = []

          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------

      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil'.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:11:32)
      * Found cython 3.0.2
      * USE_PKGCONFIG: True
      * Found conda env: ``/Users/ziliangluo/anaconda3/envs/stlearn``
      * Found HDF5 headers at ``/Users/ziliangluo/anaconda3/envs/stlearn/include``, library at ``/Users/ziliangluo/anaconda3/envs/stlearn/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Found bzip2 headers at ``/Users/ziliangluo/anaconda3/envs/stlearn/include``, library at ``/Users/ziliangluo/anaconda3/envs/stlearn/lib``.
      * Found blosc headers at ``/Users/ziliangluo/anaconda3/envs/stlearn/include``, library at ``/Users/ziliangluo/anaconda3/envs/stlearn/lib``.
      * Found blosc2 headers at ``/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/include``, library at ``/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib``.
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/Users/ziliangluo/anaconda3/envs/stlearn/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ziliangluo/anaconda3/envs/stlearn/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ziliangluo/anaconda3/envs/stlearn/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/fg/p2x2kmxd40j8spxprkrx7sth0000gn/T/pip-build-env-ddoe8iz7/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by duypham2108** [comment]
We are not available to test the conda-forge with Mac yet.
For the pip installation, can you try to use conda to install pytables first

**Comment by Kennyluo4** [comment]
Thanks for the suggestion! 
I have tried the pytables installation before but still failed to install the stLearn. Recently, I uninstalled my conda, which was downloaded from Miniconda website ([Miniconda3 macOS Apple M1 64-bit bash](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh)), and reinstalled it using homebrew. Everything is working now.
