### ISSUE TITLE
After Downloading environment and stlearn,  when I start stlearn launch this error occurs: ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

### ISSUE THREAD

**Issue by marnixwkoops** [BiomedicalMachineLearning/stLearn#284]
(stlearn) C:\>stlearn launch
Traceback (most recent call last):
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\Scripts\stlearn.exe\__main__.py", line 4, in <module>
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\stlearn\__init__.py", line 9, in <module>
    from . import pp
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\stlearn\pp.py", line 1, in <module>
    from .preprocessing.filter_genes import filter_genes
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\stlearn\preprocessing\filter_genes.py", line 5, in <module>
    import scanpy
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\scanpy\__init__.py", line 16, in <module>
    from ._utils import check_versions
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\scanpy\_utils\__init__.py", line 28, in <module>
    from .compute.is_constant import is_constant
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\scanpy\_utils\compute\is_constant.py", line 5, in <module>
    from numba import njit
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\numba\__init__.py", line 55, in <module>
    _ensure_critical_deps()
  File "C:\Users\060422\AppData\Local\anaconda3\envs\stlearn\lib\site-packages\numba\__init__.py", line 40, in _ensure_critical_deps
    raise ImportError(msg)
ImportError: Numba needs NumPy 1.22 or greater. Got NumPy 1.21.

I followed all the steps, what is going wrong?

**Comment by nnnanchen** [comment]
I have the same problem.Did you solve this problem？

**Comment by nnnanchen** [comment]
You can lower the version of Numba
